FROM ubuntu:noble AS package_xml_files_cacher

WORKDIR /ws/src

COPY . project/

RUN mkdir -p /tmp/ws/src \
 && find ./ -name "package.xml" | xargs cp --parents -t /tmp/ws/src \
 && find ./ -name "COLCON_IGNORE" | xargs cp --parents -t /tmp/ws/src \
 || true

FROM ubuntu:noble AS vesc_service_image_base

ARG USER=developer
ARG GROUP=developer

ENV ROS_DISTRO=jazzy

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /root

RUN apt update \
 && apt install --no-install-recommends -y \
    adduser \
    bash-completion \
    ccache \
    curl \
    git \
    htop \
    locate \
    mc \
    nano \
    psmisc \
    python-is-python3 \
    python3-pip \
    python3-venv \
    screen \
    sudo \
    tmux \
    vim \
    wget \
    xterm \
 && rm -rf /var/lib/apt/lists/*

RUN apt update \
 && apt install -y \
    tzdata \
 && ln -fs /usr/share/zoneinfo/America/Argentina/Buenos_Aires /etc/localtime \
 && dpkg-reconfigure --frontend noninteractive tzdata \
 && rm -rf /var/lib/apt/lists/*

FROM vesc_service_image_base AS vesc_service_image_devel

RUN apt update && sudo apt install curl -y \
   && export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') \
   && curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" \
   && sudo dpkg -i /tmp/ros2-apt-source.deb \
   && rm -rf /var/lib/apt/lists/*

RUN apt update \
 && apt install --no-install-recommends -y \
    ros-$ROS_DISTRO-ros-base \
    ros-dev-tools \
 && rm -rf /var/lib/apt/lists/*

RUN userdel ubuntu \
 && addgroup --gid 1000 $GROUP \
 && adduser --uid 1000 --ingroup $GROUP --home /home/$USER --shell /bin/bash --disabled-password --gecos "" $USER \
 && adduser $USER sudo \
 && adduser $USER dialout \
 && echo "$USER ALL=NOPASSWD: ALL" >> /etc/sudoers.d/$USER

USER $USER:$GROUP

ENV USER_WS /home/$USER/ws
RUN mkdir -p $USER_WS/src

WORKDIR $USER_WS

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml \
 && colcon mixin update default

COPY --chown=$USER:$GROUP docker/files/colcon_defaults.yaml /home/$USER/.colcon/defaults.yaml

#
# Install the project's dependencies

RUN sudo rosdep init && rosdep update

COPY --from=package_xml_files_cacher --chown=$USER:$GROUP /tmp/ws/ $USER_WS/
RUN /bin/bash -c '\
    sudo apt update \
 && rosdep install -i -y --from-path src \
 && sudo rm -rf /var/lib/apt/lists/*'

#
# Fixuid setup

COPY --chown=root:root docker/files/fixuid_config.yml /etc/fixuid/config.yml
RUN /bin/bash -c '\
    ARCH=`uname -m` && if [ "$ARCH" == "aarch64" ]; then FIXUID_ARCH="arm64"; else FIXUID_ARCH="amd64"; fi \
 && curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.6.0/fixuid-0.6.0-linux-$FIXUID_ARCH.tar.gz | sudo tar -C /usr/local/bin -xzf - \
 && sudo chmod 4755 /usr/local/bin/fixuid \
 && cd /etc/fixuid \
 && sudo sed -i "s/_USER_/$USER/" config.yml \
 && sudo sed -i "s/_GROUP_/$GROUP/" config.yml \
 && echo Done installing fixuid for $FIXUID_ARCH'

#
# Final setup of the workspace


RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/$USER/.bashrc

RUN mkdir -p $USER_WS/persistence && chmod 777 $USER_WS/persistence

RUN sudo updatedb && sudo apt update

ENV WITHIN_DEV=1

COPY --chown=root:root docker/files/fixuid_wrapper.sh /fixuid_wrapper.sh
COPY --chown=root:root docker/files/entrypoint.sh /ros_entrypoint.sh

CMD        ["/bin/bash"]
ENTRYPOINT ["/fixuid_wrapper.sh", "fixuid", "-q", "/ros_entrypoint.sh"]
