

# Yaw, Pitch, Roll in degrees
geometry_msgs/Vector3  ypr

# Linear acceleration in g (multiples of gravitational acceleration, 1g = 9.80665 m/s²)
geometry_msgs/Vector3  linear_acceleration

# Angular velocity in degrees/second
geometry_msgs/Vector3  angular_velocity

# Magnetic field in raw magnetometer units
geometry_msgs/Vector3  compass

# Orientation quaternion (unitless)
geometry_msgs/Quaternion orientation
